<script setup>
import Fit from './layouts/Fit.vue'
import HorizontalScroll         from './components/HorizontalScroll.vue'
import HorizontalScrollElement  from './components/HorizontalScrollElement.vue'
import HorizontalScrollElements from './components/HorizontalScrollElements.vue'
import HorizontalScrolls        from './components/HorizontalScrolls.vue'
import HorizontalScrollTitle    from './components/HorizontalScrollTitle.vue'
</script>

<template>
  <Fit>
		<HorizontalScrolls>
			<HorizontalScroll>
				<HorizontalScrollTitle/>
				<HorizontalScrollElements>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
				</HorizontalScrollElements>
			</HorizontalScroll>

			<HorizontalScroll>
				<HorizontalScrollTitle/>
				<HorizontalScrollElements>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
				</HorizontalScrollElements>
			</HorizontalScroll>

			<HorizontalScroll>
				<HorizontalScrollTitle/>
				<HorizontalScrollElements>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
				</HorizontalScrollElements>
			</HorizontalScroll>

			<HorizontalScroll>
				<HorizontalScrollTitle/>
				<HorizontalScrollElements>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
				</HorizontalScrollElements>
			</HorizontalScroll>

			<HorizontalScroll>
				<HorizontalScrollTitle/>
				<HorizontalScrollElements>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
				</HorizontalScrollElements>
			</HorizontalScroll>

			<HorizontalScroll>
				<HorizontalScrollTitle/>
				<HorizontalScrollElements>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
					<HorizontalScrollElement/>
				</HorizontalScrollElements>
			</HorizontalScroll>
		</HorizontalScrolls>
	</Fit>
</template>
